// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Sex")]
            public string Sex { get; set; }

            [ColumnName(@"ChestPainType")]
            public string ChestPainType { get; set; }

            [ColumnName(@"RestingBP")]
            public float RestingBP { get; set; }

            [ColumnName(@"Cholesterol")]
            public float Cholesterol { get; set; }

            [ColumnName(@"FastingBS")]
            public float FastingBS { get; set; }

            [ColumnName(@"RestingECG")]
            public string RestingECG { get; set; }

            [ColumnName(@"MaxHR")]
            public float MaxHR { get; set; }

            [ColumnName(@"ExerciseAngina")]
            public bool ExerciseAngina { get; set; }

            [ColumnName(@"Oldpeak")]
            public float Oldpeak { get; set; }

            [ColumnName(@"ST_Slope")]
            public string ST_Slope { get; set; }

            [ColumnName(@"HeartDisease")]
            public float HeartDisease { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
