
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace MLModel1_ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                Age = 40F,
                Sex = @"M",
                ChestPainType = @"ATA",
                RestingBP = 140F,
                Cholesterol = 289F,
                FastingBS = 0F,
                RestingECG = @"Normal",
                MaxHR = 172F,
                Oldpeak = 0F,
                ST_Slope = @"Up",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual HeartDisease with predicted HeartDisease from sample data...\n\n");


            Console.WriteLine($"Age: {40F}");
            Console.WriteLine($"Sex: {@"M"}");
            Console.WriteLine($"ChestPainType: {@"ATA"}");
            Console.WriteLine($"RestingBP: {140F}");
            Console.WriteLine($"Cholesterol: {289F}");
            Console.WriteLine($"FastingBS: {0F}");
            Console.WriteLine($"RestingECG: {@"Normal"}");
            Console.WriteLine($"MaxHR: {172F}");
            Console.WriteLine($"Oldpeak: {0F}");
            Console.WriteLine($"ST_Slope: {@"Up"}");
            Console.WriteLine($"HeartDisease: {0F}");


            Console.WriteLine($"\n\nPredicted HeartDisease: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
